#!/Users/fran/.nvm/versions/node/v24.15.0/bin/node

// Required parameters:
// @raycast.schemaVersion 1
// @raycast.title Create an Alias
// @raycast.mode fullOutput

// Optional parameters:
// @raycast.icon 🤐
// @raycast.argument3 { "type": "text", "placeholder": "number of names (3)", "optional": true }

// Documentation:
// @raycast.description Generate first and last name combinations to maintain anonymity.
// @raycast.author fgrgic
// @raycast.authorURL https://frangrgic.com

const [numberOfNames] = process.argv.slice(2);

const NUMBER_OF_NAMES = numberOfNames ? parseInt(numberOfNames) : 3;

const firstMNamesHr = [
  "ivan",
  "josip",
  "marko",
  "stjepan",
  "tomislav",
  "željko",
  "ivica",
  "ante",
  "mario",
  "nikola",
  "petar",
  "franjo",
  "milan",
  "damir",
  "branko",
  "marijan",
  "vladimir",
  "darko",
  "zlatko",
  "goran",
  "mirko",
  "zdravko",
  "miroslav",
  "zoran",
  "slavko",
  "davor",
  "dragutin",
  "mladen",
  "boris",
  "igor",
  "dražen",
  "vlado",
  "robert",
  "zvonko",
  "dragan",
  "ivo",
  "danijel",
  "drago",
  "mato",
  "nenad",
  "zvonimir",
  "luka",
  "đuro",
  "vinko",
  "hrvoje",
  "mijo",
  "krešimir",
  "božidar",
  "denis",
  "zdenko",
  "matija",
  "jure",
  "siniša",
  "ilija",
  "dario",
  "andrija",
  "filip",
  "antonio",
  "karlo",
  "matej",
  "david",
  "marin",
  "mateo",
  "toni",
  "leon",
  "erik",
  "jakov",
  "stipe",
  "mate",
  "janko",
  "domagoj",
  "vedran",
  "alan",
  "alen",
  "bojan",
  "dejan",
  "silvio",
  "bruno",
  "sven",
  "lovro",
  "patrik",
  "rafael",
  "roko",
  "tin",
  "noa",
  "gabriel",
  "mihael",
  "jan",
  "vito",
  "lovre",
  "frane",
  "šime",
  "božo",
  "jozo",
  "juraj",
  "niko",
  "teo",
  "dominik",
  "matko",
  "anteo",
];
const firstFNamesHr = [
  "marija",
  "ana",
  "ivana",
  "mirjana",
  "katarina",
  "nada",
  "dragica",
  "ljubica",
  "vesna",
  "marina",
  "katica",
  "sanja",
  "marica",
  "snježana",
  "maja",
  "ivanka",
  "branka",
  "kata",
  "ljiljana",
  "jelena",
  "anka",
  "mira",
  "kristina",
  "martina",
  "jadranka",
  "nevenka",
  "ankica",
  "marijana",
  "slavica",
  "željka",
  "danica",
  "anica",
  "ružica",
  "zdenka",
  "milka",
  "jasna",
  "anita",
  "mara",
  "danijela",
  "dubravka",
  "sandra",
  "đurđica",
  "iva",
  "josipa",
  "lidija",
  "štefica",
  "biserka",
  "renata",
  "irena",
  "vera",
  "ruža",
  "božica",
  "nikolina",
  "suzana",
  "milica",
  "tatjana",
  "nataša",
  "antonija",
  "zorica",
  "petra",
  "matea",
  "lucija",
  "lana",
  "sara",
  "ema",
  "nika",
  "lara",
  "mia",
  "tea",
  "valentina",
  "nina",
  "ena",
  "leona",
  "paula",
  "dora",
  "marta",
  "franka",
  "laura",
  "gabrijela",
  "magdalena",
  "helena",
  "karla",
  "lorena",
  "elena",
  "monika",
  "dijana",
  "tanja",
  "barbara",
  "silvija",
  "ines",
  "ema",
  "maša",
  "mila",
  "rita",
  "noa",
  "gabriela",
  "klara",
  "stela",
  "dorotea",
  "marcela",
];
const lastNamesHr = [
  "horvat",
  "kovačević",
  "babić",
  "marić",
  "jurić",
  "novak",
  "kovačić",
  "knežević",
  "vuković",
  "marković",
  "matić",
  "petrović",
  "tomić",
  "perić",
  "božić",
  "pavlović",
  "blažević",
  "lovrić",
  "bošnjak",
  "grgić",
  "brkić",
  "filipović",
  "vidović",
  "jukić",
  "martinović",
  "mandić",
  "šimunović",
  "nikolić",
  "jurković",
  "barišić",
  "lončar",
  "živković",
  "šimić",
  "rukavina",
  "perković",
  "vučković",
  "lukić",
  "matijević",
  "novosel",
  "klarić",
  "matković",
  "pavić",
  "bašić",
  "antunović",
  "marušić",
  "ćosić",
  "kovač",
  "miletić",
  "posavec",
  "kralj",
  "varga",
  "marjanović",
  "popović",
  "cindrić",
  "grubišić",
  "jakovljević",
  "dujmović",
  "novaković",
  "jurišić",
  "brajković",
  "ivančić",
  "galić",
  "bilić",
  "ivanković",
  "šimunić",
  "jozić",
  "crnković",
  "janković",
  "burić",
  "vrdoljak",
  "kolarić",
  "mitrović",
  "mikulić",
  "radić",
  "dragičević",
  "lučić",
  "vukelić",
  "đurđević",
  "jovanović",
  "grgurić",
  "jurčević",
  "vidaković",
  "petković",
  "ružić",
  "herceg",
  "abramović",
  "šarić",
  "đurić",
  "pavlić",
  "lončarić",
  "stanić",
  "butković",
  "cvitković",
  "katić",
  "krznarić",
  "josipović",
  "ivanović",
  "golubić",
  "jelić",
  "sever",
];
const firstMNamesEn = [
  "james",
  "michael",
  "john",
  "robert",
  "david",
  "william",
  "richard",
  "joseph",
  "thomas",
  "christopher",
  "charles",
  "daniel",
  "matthew",
  "anthony",
  "mark",
  "donald",
  "steven",
  "paul",
  "andrew",
  "joshua",
  "kenneth",
  "kevin",
  "brian",
  "george",
  "timothy",
  "ronald",
  "edward",
  "jason",
  "jeffrey",
  "ryan",
  "jacob",
  "gary",
  "nicholas",
  "eric",
  "jonathan",
  "stephen",
  "larry",
  "justin",
  "scott",
  "brandon",
  "benjamin",
  "samuel",
  "gregory",
  "alexander",
  "patrick",
  "frank",
  "raymond",
  "jack",
  "dennis",
  "jerry",
  "tyler",
  "aaron",
  "henry",
  "douglas",
  "peter",
  "adam",
  "zachary",
  "nathan",
  "walter",
  "harold",
  "kyle",
  "carl",
  "arthur",
  "gerald",
  "roger",
  "keith",
  "jeremy",
  "terry",
  "lawrence",
  "sean",
  "christian",
  "albert",
  "joe",
  "ethan",
  "austin",
  "jesse",
  "willie",
  "billy",
  "bryan",
  "bruce",
  "noah",
  "liam",
  "oliver",
  "elijah",
  "lucas",
  "mason",
  "logan",
  "owen",
  "levi",
  "leo",
  "theodore",
  "hudson",
  "ezra",
  "asher",
  "isaac",
  "luke",
  "julian",
  "wyatt",
  "carter",
  "caleb",
];
const firstFNamesEn = [
  "mary",
  "patricia",
  "jennifer",
  "linda",
  "elizabeth",
  "barbara",
  "susan",
  "jessica",
  "karen",
  "sarah",
  "lisa",
  "nancy",
  "betty",
  "sandra",
  "ashley",
  "kimberly",
  "emily",
  "donna",
  "margaret",
  "michelle",
  "carol",
  "amanda",
  "melissa",
  "deborah",
  "stephanie",
  "rebecca",
  "sharon",
  "laura",
  "cynthia",
  "dorothy",
  "amy",
  "kathleen",
  "angela",
  "shirley",
  "brenda",
  "emma",
  "anna",
  "pamela",
  "nicole",
  "samantha",
  "katherine",
  "christine",
  "helen",
  "debra",
  "rachel",
  "carolyn",
  "janet",
  "catherine",
  "maria",
  "heather",
  "diane",
  "ruth",
  "julie",
  "olivia",
  "joyce",
  "virginia",
  "victoria",
  "kelly",
  "lauren",
  "christina",
  "joan",
  "evelyn",
  "judith",
  "megan",
  "cheryl",
  "andrea",
  "hannah",
  "jacqueline",
  "martha",
  "gloria",
  "teresa",
  "ann",
  "sara",
  "madison",
  "frances",
  "kathryn",
  "janice",
  "jean",
  "abigail",
  "alice",
  "julia",
  "judy",
  "sophia",
  "grace",
  "isabella",
  "ava",
  "mia",
  "amelia",
  "charlotte",
  "harper",
  "evelyn",
  "ella",
  "scarlett",
  "chloe",
  "lily",
  "zoe",
  "nora",
  "hazel",
  "violet",
  "aurora",
];
const lastNamesEn = [
  "smith",
  "jones",
  "williams",
  "brown",
  "johnson",
  "taylor",
  "davis",
  "miller",
  "wilson",
  "thompson",
  "thomas",
  "anderson",
  "white",
  "martin",
  "moore",
  "jackson",
  "clark",
  "walker",
  "evans",
  "lee",
  "lewis",
  "king",
  "harris",
  "roberts",
  "robinson",
  "wright",
  "young",
  "scott",
  "reed",
  "murphy",
  "hill",
  "wood",
  "hall",
  "green",
  "allen",
  "kelly",
  "campbell",
  "edwards",
  "adams",
  "baker",
  "watson",
  "mitchell",
  "phillips",
  "cooper",
  "turner",
  "morris",
  "carter",
  "morgan",
  "hughes",
  "cook",
  "ward",
  "collins",
  "james",
  "parker",
  "bell",
  "nelson",
  "stewart",
  "bailey",
  "stevens",
  "cox",
  "bennett",
  "murray",
  "rogers",
  "gray",
  "price",
  "ryan",
  "mcdonald",
  "russell",
  "richardson",
  "harrison",
  "sanders",
  "walsh",
  "simpson",
  "marshall",
  "ross",
  "perry",
  "kennedy",
  "graham",
  "foster",
  "shaw",
  "ellis",
  "fisher",
  "butler",
  "reynolds",
  "fox",
  "robertson",
  "barnes",
  "chapman",
  "powell",
  "mason",
  "henderson",
  "hamilton",
  "peterson",
  "howard",
  "brooks",
  "griffin",
  "palmer",
  "stone",
  "hunt",
  "mills",
];

const generateHrName = (gender) => {
  switch (gender) {
    case "m":
      return (
        firstMNamesHr[Math.floor(Math.random() * firstMNamesHr.length)] +
        " " +
        lastNamesHr[Math.floor(Math.random() * lastNamesHr.length)]
      );
    case "f":
      return (
        firstFNamesHr[Math.floor(Math.random() * firstFNamesHr.length)] +
        " " +
        lastNamesHr[Math.floor(Math.random() * lastNamesHr.length)]
      );
    default:
      const allFirstNames = [...firstMNamesHr, ...firstFNamesHr];
      return (
        allFirstNames[Math.floor(Math.random() * allFirstNames.length)] +
        " " +
        lastNamesHr[Math.floor(Math.random() * lastNamesHr.length)]
      );
  }
};

const generateEnName = (gender) => {
  switch (gender) {
    case "m":
      return (
        firstMNamesEn[Math.floor(Math.random() * firstMNamesEn.length)] +
        " " +
        lastNamesEn[Math.floor(Math.random() * lastNamesEn.length)]
      );
    case "f":
      return (
        firstFNamesEn[Math.floor(Math.random() * firstFNamesEn.length)] +
        " " +
        lastNamesEn[Math.floor(Math.random() * lastNamesEn.length)]
      );
    default:
      const allFirstNames = [...firstMNamesEn, ...firstFNamesEn];
      return (
        allFirstNames[Math.floor(Math.random() * allFirstNames.length)] +
        " " +
        lastNamesEn[Math.floor(Math.random() * lastNamesEn.length)]
      );
  }
};

const generateRandomName = (gender, language) => {
  switch (language) {
    case "en":
      return generateEnName(gender);
    case "hr":
      return generateHrName(gender);
    default:
      return Math.random() < 0.5
        ? generateEnName(gender)
        : generateHrName(gender);
  }
};

const generateNames = (gender) => {
  const hrNames = [];
  const enNames = [];
  for (let i = 0; i < NUMBER_OF_NAMES; i++) {
    hrNames.push(generateHrName(gender));
    enNames.push(generateEnName(gender));
  }
  return { hrNames, enNames };
};

const { hrNames: hrMaleNames, enNames: enMaleNames } = generateNames("m");
const { hrNames: hrFemaleNames, enNames: enFemaleNames } = generateNames("f");
console.log("HR NAMES:");
console.log("--------------------------------");
console.log(hrMaleNames.join("\n"));
console.log("--------------------------------");
console.log(hrFemaleNames.join("\n"));
console.log("\n");
console.log("EN NAMES:");
console.log("--------------------------------");
console.log(enMaleNames.join("\n"));
console.log("--------------------------------");
console.log(enFemaleNames.join("\n"));
console.log("--------------------------------");
